@SerfinsaBackend_HostAddress = https://localhost:7288

###

POST {{SerfinsaBackend_HostAddress}}/api/tareas
Content-Type: application/json

{
  "titulo": "Preparar tareas de la universidad",
  "descripcion": "Concluir con las tareas que hacen falta",
  "prioridad": "Alta",
  "completada": false,
  "fechaCreacion": "2026-08-30T..."
}

###

@id=1
GET {{SerfinsaBackend_HostAddress}}/api/Tareas/{{id}}

###

GET {{SerfinsaBackend_HostAddress}}/api/tareas

###
GET {{SerfinsaBackend_HostAddress}}/api/tareas?estado=pendientes

###

GET {{SerfinsaBackend_HostAddress}}/api/tareas?estado=completadas
